### ISSUE TITLE
broken on python3

### ISSUE THREAD

**Issue by Seegras** [andresriancho/enumerate-iam#3]
$ python3 ./enumerate-iam.py 
Traceback (most recent call last):
  File "./enumerate-iam.py", line 4, in <module>
    from enumerate_iam.main import enumerate_iam
  File "/home/pkeel/git/enumerate-iam/enumerate_iam/main.py", line 135
    def check_one_permission((access_key, secret_key, session_token, region, service_name, operation_name)):
                             ^
SyntaxError: invalid syntax

**Comment by andresriancho** [comment]
Should work now, please let me know if you find any other py3k issues. Thanks!
